@startuml Akenasia
left to right direction

class Chronometre {
  chronometre : CHRONOMETER
  pos : POSITION
  place : PLACE
  Chronometre()
  nouvelEssai()
}

class Place {
  placeId : INTEGER
  placeName : STRING
  placeLat : DOUBLE
  placeLong : DOUBLE
  Place()
}

class Database {
  saveRecord()
  orderRecord()
  viewRecord()
  deleteRecord()
}

class Position {
  latitude : DOUBLE
  longitude : DOUBLE
  Position()
  refreshLocation()
  calcul_distance() : DOUBLE
}

interface MyListAdapter {
  getView()
}

class Game {
  pos : POSITION
  place : PLACE
  Game()
}

class CoupsLimites {
  essais : INTEGER
  pos : POSITION
  place : PLACE
  lastDistance : DOUBLE
  CoupsLimites()
  nouvelEssai()
}

class PositionTable {
  posId : INTEGER
  posLat : DOUBLE
  posLong : DOUBLE
  partieId : INTEGER
}

interface PositionAdapter {
  getView()
}

class Historique {
  partieId : INTEGER
  viewRecord()
}

class DatabaseHandler {
  addPlace()
  viewPlace()
  updatePlace()
  deletePlace()
}

Database <|-- MyListAdapter
DatabaseHandler <|-- Database
Place <|-- Database
Position <|-- Place
Place <|-- Game
Game <|-- Chronometre
Game <|-- CoupsLimites
Chronometre <|-- PositionTable
CoupsLimites <|-- PositionTable
PositionTable <|-- PositionAdapter
PositionTable <|-- Historique

@enduml