@startuml Akenasia
left to right direction

class Chronometre {
  chronometre : CHRONOMETER
  pos : POSITION
  place : PLACE
  googleMap : GOOGLEMAP
  dbHandler : DATASABASEHANDLER
  i : INTEGER
  onMapReady(map: GOOGLEMAP)
  Chronometre()
  nouvelEssai()
}

class Place {
  placeId : INTEGER
  placeName : STRING
  placeLat : DOUBLE
  placeLong : DOUBLE
  Place()
}

class Database {
  saveRecord()
  orderRecord()
  viewRecord()
  deleteRecord()
}

class Position {
  latitude : DOUBLE
  longitude : DOUBLE
  Position()
  refreshLocation()
  calcul_distance() : DOUBLE
}

interface MyListAdapter {
  getView()
}

class Gamemode {
  Gamemode()
}

class CoupsLimites {
  essais : INTEGER
  pos : POSITION
  place : PLACE
  dbHandler : DATASABASEHANDLER
  i : INTEGER
  lastDistance : DOUBLE
  CoupsLimites()
  nouvelEssai()
}

class PositionTable {
  posId : INTEGER
  posLat : DOUBLE
  posLong : DOUBLE
  partieId : INTEGER
}

interface PositionAdapter {
  getView()
}

class Historique {
  partieId : INTEGER
  googleMap : GOOGLEMAP
  onMapReady(map: GOOGLEMAP)
  onInfoWindowClick(marker: Marker) 
  updateTitle(marker: Marker) : STRING
  updateInfo(marker: Marker) : STRING
}

class DatabaseHandler {
  addPlace()
  viewPlace()
  updatePlace()
  deletePlace()
}

class MarkerDialog {
  title : STRING
  info : STRING
  setTitle()
  setInfo()
}

class PoiDialog {
  name : STRING
  latlong : STRING
  setName()
  setLatLong()
  use()
}

class Item {
  itemId : INTEGER
  itemName : STRING
  itemDesc : STRING
  Item()
}

interface ItemAdapter {
  getView()
}

interface GamemodeFactory {
  googleMap: GOOGLEMAP
  pos: POSITION
  dbHandler : DATASABASEHANDLER
  place: PLACE
  i: INTEGER
}

class OpenWorld {
  pos : POSITION
  cameraFocus : BOOLEAN
  googleMap : GOOGLEMAP
  chronometre : CHRONOMETER
  cameraSwitch()
  itemSelected()
  onMapReady(map: GOOGLEMAP)
  onPoiClick(poi: PointOfInterest)
  updateName(poi: PointOfInterest) : STRING
  updateLatLong(poi: PointOfInterest) : STRING
}

Database <|-- MyListAdapter
DatabaseHandler <|-- Database
Place <|-- Database
Position <|-- Place
Place <|-- Gamemode
GamemodeFactory <|-- Chronometre
GamemodeFactory <|-- CoupsLimites
Chronometre <|-- PositionTable
CoupsLimites <|-- PositionTable
PositionTable <|-- PositionAdapter
PositionTable <|-- Historique
Historique <|-- MarkerDialog
OpenWorld <|-- PoiDialog
Gamemode <|-- OpenWorld
OpenWorld <|-- Item
Item <|-- ItemAdapter
Gamemode <|-- GamemodeFactory 

@enduml